model:
  model_name: "model_path_folder or model_name_hf"
  new_model: "semikong-8b"
  dataset_name: "dataset_path_folder or dataset_name_hf"
  use_4bit: True
  use_nested_quant: False
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_quant_type: "nf4"
  max_seq_length: None
  output_dir: "./results"
  device_map: {"": 0}

training:
  num_train_epochs: 2
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  learning_rate: 2e-4
  max_grad_norm: 0.3
  weight_decay: 0.001
  fp16: False
  bf16: False
  packing: False
  gradient_checkpointing: True
  optim: "paged_adamw_32bit"
  lr_scheduler_type: "cosine"
  max_steps: -1
  warmup_ratio: 0.03
  group_by_length: True
  save_steps: 10
  logging_steps: 1

lora:
  lora_alpha: 16
  lora_dropout: 0.1
  lora_r: 64
